name: Rebase PR target

on: [pull_request_target]

permissions: read-all

jobs:
  _:
    permissions:
      contents: read # for ljharb/rebase to push code to rebase
      pull-requests: read # for ljharb/rebase to get info about PR
    name: "Automatic Rebase"

    runs-on: ubuntu-latest

    steps:
    - uses: step-security/harden-runner@99bb20354f6d4c1786dc4a0d0817d8ce8862affe # rc
      with:
        egress-policy: audit
    - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      with:
       fetch-depth: 0
    - uses: ljharb/rebase@6ca8681dc61847335eb68c8e43f4becb0911c091
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
