name: Wait-for-secrets Demo
on:
  workflow_dispatch
  
jobs:
  build:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: step-security/wait-for-secrets@main
        id: get-otp
        with:
          secrets: |
            DUMMY_SECRET: 
              name: 'Dummy secret'
              description: 'Dummy secret to demo wait-for-secrets'
      - run: | 
          echo ${{ steps.get-otp.outputs.DUMMY_SECRET }}
